on:
  pull_request:
    paths:
      - 'packages/@momentum-design/momentum-automation-center/test/**'
      - 'packages/@momentum-design/momentum-automation-center/src/**'
      - 'packages/@momentum-design/momentum-automation-center/raw/2022/**'
name: Test
jobs:
  test:
    name: Test pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'momentum-design' }}
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
          fetch-depth: 2
    - name: Install Yarn
      run: yarn
    - name: Install Package and Build
      run: yarn workspace @momentum-design/momentum-automation-center init-build
    - name: check color updates
      run: yarn workspace @momentum-design/momentum-automation-center gen-color actor=${{ github.actor }} token=${{ secrets.MOMENTUM_TOKEN }} tokenWebex=${{ secrets.WEBEX_TOKEN }}
    - name: check font updates
      run: yarn workspace @momentum-design/momentum-automation-center gen-font actor=${{ github.actor }} token=${{ secrets.MOMENTUM_TOKEN }} tokenWebex=${{ secrets.WEBEX_TOKEN }}
    - name: check icon updates
      run: yarn workspace @momentum-design/momentum-automation-center gen-icon diffOnly=true actor=${{ github.actor }} token=${{ secrets.MOMENTUM_TOKEN }} tokenWebex=${{ secrets.WEBEX_TOKEN }}
    - name: check illustration updates
      run: yarn workspace @momentum-design/momentum-automation-center gen-illustration diffOnly=true actor=${{ github.actor }} token=${{ secrets.MOMENTUM_TOKEN }} tokenWebex=${{ secrets.WEBEX_TOKEN }}
    - name: Test release data
      run: yarn workspace @momentum-design/momentum-automation-center test