on:
  workflow_dispatch:
  
name: Publish To NPM
jobs:
  jobAutomation:
    name: Sync momentum-abstract data
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'momentum-design' }}
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Install Package and Build
      run: yarn workspace @momentum-design/momentum-abstract-builder init-build
    - name: Publish
      run: yarn workspace @momentum-design/momentum-abstract-builder sync
    - name: config 
      run: |
        git config --global user.email "automation@cisco.com"
        git config --global user.name "Automation"
    - name: commit new release
      run: yarn workspace @momentum-design/momentum-abstract-builder commit token=${{ secrets.ACTION_TOKEN }} repository=${{github.repository}}

